[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AffineMaps = "2c83c9a8-abf5-4329-a0d7-deffaf474661"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
BAT = "c0cd4b16-88b7-57fa-983b-ab80aecada7e"
BinnedModels = "fa1fc709-16e9-4084-816c-4cfb0f07afb9"
BitOperations = "e1e0eea2-bc69-5bf6-8574-13634873a17c"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
CodecZstd = "6b39b394-51ab-5f42-8807-6242bab2b4c2"
CompositionsBase = "a33af91c-f02d-484b-be07-31d278c5ca2b"
ConcurrentCollections = "5060bff5-0b44-40c5-b522-fcd3ca5cecdd"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Curry = "e4be5ba2-6463-56d8-8409-50d2cdcb556e"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
EmpiricalDistributions = "0bbb1fad-0f24-45fe-94a4-415852c5cc3b"
EncodedArrays = "97725368-735e-11e9-0dd7-6bf34c3b13a8"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
FunctionChains = "8e6b2b91-af83-483e-ba35-d00930e4cf9b"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
GaussianMixtures = "cc18c42c-b769-54ff-9e2a-b28141a64aae"
Geant4 = "559df036-b7a0-42fd-85df-7d5dd9d70f44"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
H5Zzstd = "f6f2d980-1ec6-471c-a70d-0270e22f1103"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HeterogeneousComputing = "2182be2a-124f-4a91-8389-f06db5907a21"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
IrrationalConstants = "92d709cd-6900-40b7-9082-c6be49f344b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LegendDSP = "e6d7a502-be5c-5049-a927-8d60e566555d"
LegendDataManagement = "9feedd95-f0e0-423f-a8dc-de0970eae6b3"
LegendDataTypes = "99e09c13-5545-5ee2-bfa2-77f358fb75d8"
LegendEventAnalysis = "ca666546-4c2a-41e4-9648-72713d810efe"
LegendHDF5IO = "c9265ca6-b027-5446-b1a4-febfa8dd10b0"
LegendMakie = "ce9a434a-d062-4f11-9371-3059ddb1c48a"
LegendSpecFits = "18221496-77af-46cf-bab8-820da09f7f97"
LegendTestData = "33d6da08-6349-5f7c-b5a4-6ff4d8795aaf"
LegendTextIO = "c397c909-374d-579b-8af3-fa3aa4f02e89"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
LuxLib = "82251201-b29d-42c6-8e01-566dec8acb11"
MGVI = "fdae7790-d271-4276-880d-f72bbddf129c"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
MeasureBase = "fa1605e6-acd5-459c-a1e6-7e635759db14"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OptimizationBase = "bca83a33-5cc9-4baa-983d-23429ab6bcbb"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
ParallelProcessingTools = "8e8a01fc-6193-5ca1-a2f1-20776dae4199"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PropDicts = "4dc08600-4268-439e-8673-d706fafbb426"
PropertyFunctions = "09e99361-2bb8-48a2-a80f-de58f0739eb4"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RadiationDetectorDSP = "afd6e06f-c550-5763-af36-7391d39e46ec"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"
RadiationSpectra = "4f207c7e-01da-51d7-a1a0-c8c06dd1d883"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SolidStateDetectors = "71e43887-2bd9-5f77-aebd-47f656f0a3f0"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticStrings = "4db0a0c5-418a-4e1d-8806-cb305fe13294"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
UnROOT = "3cd96dde-e98d-4713-81e9-a4a1b0235ce9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"
ValueShapes = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
BlackBoxOptim = {rev = "master", url = "https://github.com/robertfeldt/BlackBoxOptim.jl.git"}
LegendDSP = {path = "../pkgrepos/LegendDSP"}
LegendDataManagement = {path = "../pkgrepos/LegendDataManagement"}
LegendDataTypes = {path = "../pkgrepos/LegendDataTypes"}
LegendEventAnalysis = {path = "../pkgrepos/LegendEventAnalysis"}
LegendHDF5IO = {path = "../pkgrepos/LegendHDF5IO"}
LegendMakie = {path = "../pkgrepos/LegendMakie"}
LegendSpecFits = {path = "../pkgrepos/LegendSpecFits"}
LegendTestData = {path = "../pkgrepos/LegendTestData"}
LegendTextIO = {path = "../pkgrepos/LegendTextIO"}
RadiationDetectorDSP = {path = "../pkgrepos/RadiationDetectorDSP"}
RadiationDetectorSignals = {path = "../pkgrepos/RadiationDetectorSignals"}
RadiationSpectra = {path = "../pkgrepos/RadiationSpectra"}
SolidStateDetectors = {path = "../pkgrepos/SolidStateDetectors"}
